### ISSUE TITLE
Bug on call /aula@TorreArchimedeBot in a Telegram Group

### ISSUE THREAD

**Issue by matrevis** [Augugrumi/TorreArchimedeBot#40]
**This is a (check only one)**:
- [x] Bug report
- [] Feature request

**That affects**:
- [x] Telegram bot
- [] Slack bot

**Short Description of the issue/feature request**:
On a Telegram Group Bot work correctly in 3 call (/free , /now , /info ) but not work in the other call.

**Comment by mzanella** [comment]
Thanks @matrevis
